overwrite: true
schema: 'https://arweave.net/graphql'
documents: 'graphql/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-graphql-request'
